/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/buttons/ActionButton': RouteRecordInfo<'/buttons/ActionButton', '/buttons/ActionButton', Record<never, never>, Record<never, never>>,
    '/buttons/Button': RouteRecordInfo<'/buttons/Button', '/buttons/Button', Record<never, never>, Record<never, never>>,
    '/buttons/ButtonGroup': RouteRecordInfo<'/buttons/ButtonGroup', '/buttons/ButtonGroup', Record<never, never>, Record<never, never>>,
    '/buttons/Link': RouteRecordInfo<'/buttons/Link', '/buttons/Link', Record<never, never>, Record<never, never>>,
    '/buttons/SelectButton': RouteRecordInfo<'/buttons/SelectButton', '/buttons/SelectButton', Record<never, never>, Record<never, never>>,
    '/buttons/SplitButton': RouteRecordInfo<'/buttons/SplitButton', '/buttons/SplitButton', Record<never, never>, Record<never, never>>,
    '/buttons/ToggleButton': RouteRecordInfo<'/buttons/ToggleButton', '/buttons/ToggleButton', Record<never, never>, Record<never, never>>,
    '/Changelog': RouteRecordInfo<'/Changelog', '/Changelog', Record<never, never>, Record<never, never>>,
    '/Colours': RouteRecordInfo<'/Colours', '/Colours', Record<never, never>, Record<never, never>>,
    '/data/Chart': RouteRecordInfo<'/data/Chart', '/data/Chart', Record<never, never>, Record<never, never>>,
    '/data/DataView': RouteRecordInfo<'/data/DataView', '/data/DataView', Record<never, never>, Record<never, never>>,
    '/data/Progress': RouteRecordInfo<'/data/Progress', '/data/Progress', Record<never, never>, Record<never, never>>,
    '/data/StatWidget': RouteRecordInfo<'/data/StatWidget', '/data/StatWidget', Record<never, never>, Record<never, never>>,
    '/data/Table': RouteRecordInfo<'/data/Table', '/data/Table', Record<never, never>, Record<never, never>>,
    '/data/Tile': RouteRecordInfo<'/data/Tile', '/data/Tile', Record<never, never>, Record<never, never>>,
    '/data/Tree': RouteRecordInfo<'/data/Tree', '/data/Tree', Record<never, never>, Record<never, never>>,
    '/data/TreeTable': RouteRecordInfo<'/data/TreeTable', '/data/TreeTable', Record<never, never>, Record<never, never>>,
    '/examples/CodeTesting': RouteRecordInfo<'/examples/CodeTesting', '/examples/CodeTesting', Record<never, never>, Record<never, never>>,
    '/examples/components/ExampleAutoComplete': RouteRecordInfo<'/examples/components/ExampleAutoComplete', '/examples/components/ExampleAutoComplete', Record<never, never>, Record<never, never>>,
    '/examples/components/ExampleButton': RouteRecordInfo<'/examples/components/ExampleButton', '/examples/components/ExampleButton', Record<never, never>, Record<never, never>>,
    '/examples/components/ExampleConfirmDialogue': RouteRecordInfo<'/examples/components/ExampleConfirmDialogue', '/examples/components/ExampleConfirmDialogue', Record<never, never>, Record<never, never>>,
    '/examples/components/ExampleConfirmPopup': RouteRecordInfo<'/examples/components/ExampleConfirmPopup', '/examples/components/ExampleConfirmPopup', Record<never, never>, Record<never, never>>,
    '/examples/components/ExampleDataView': RouteRecordInfo<'/examples/components/ExampleDataView', '/examples/components/ExampleDataView', Record<never, never>, Record<never, never>>,
    '/examples/components/ExampleDrawer': RouteRecordInfo<'/examples/components/ExampleDrawer', '/examples/components/ExampleDrawer', Record<never, never>, Record<never, never>>,
    '/examples/components/ExampleFileUploader': RouteRecordInfo<'/examples/components/ExampleFileUploader', '/examples/components/ExampleFileUploader', Record<never, never>, Record<never, never>>,
    '/examples/components/ExampleListbox': RouteRecordInfo<'/examples/components/ExampleListbox', '/examples/components/ExampleListbox', Record<never, never>, Record<never, never>>,
    '/examples/components/ExampleModal': RouteRecordInfo<'/examples/components/ExampleModal', '/examples/components/ExampleModal', Record<never, never>, Record<never, never>>,
    '/examples/components/ExampleModalValidation': RouteRecordInfo<'/examples/components/ExampleModalValidation', '/examples/components/ExampleModalValidation', Record<never, never>, Record<never, never>>,
    '/examples/components/ExampleNavBar': RouteRecordInfo<'/examples/components/ExampleNavBar', '/examples/components/ExampleNavBar', Record<never, never>, Record<never, never>>,
    '/examples/components/ExamplePickList': RouteRecordInfo<'/examples/components/ExamplePickList', '/examples/components/ExamplePickList', Record<never, never>, Record<never, never>>,
    '/examples/components/ExampleScratchpad': RouteRecordInfo<'/examples/components/ExampleScratchpad', '/examples/components/ExampleScratchpad', Record<never, never>, Record<never, never>>,
    '/examples/components/ExampleSelectBool': RouteRecordInfo<'/examples/components/ExampleSelectBool', '/examples/components/ExampleSelectBool', Record<never, never>, Record<never, never>>,
    '/examples/components/ExampleTableExapandableGroup': RouteRecordInfo<'/examples/components/ExampleTableExapandableGroup', '/examples/components/ExampleTableExapandableGroup', Record<never, never>, Record<never, never>>,
    '/examples/components/ExampleTableGroup': RouteRecordInfo<'/examples/components/ExampleTableGroup', '/examples/components/ExampleTableGroup', Record<never, never>, Record<never, never>>,
    '/examples/components/ExampleTableWithColumnGroups': RouteRecordInfo<'/examples/components/ExampleTableWithColumnGroups', '/examples/components/ExampleTableWithColumnGroups', Record<never, never>, Record<never, never>>,
    '/examples/components/FormExamples': RouteRecordInfo<'/examples/components/FormExamples', '/examples/components/FormExamples', Record<never, never>, Record<never, never>>,
    '/examples/components/SimpleFormValidationExample': RouteRecordInfo<'/examples/components/SimpleFormValidationExample', '/examples/components/SimpleFormValidationExample', Record<never, never>, Record<never, never>>,
    '/examples/components/SimpleModalValidationExample': RouteRecordInfo<'/examples/components/SimpleModalValidationExample', '/examples/components/SimpleModalValidationExample', Record<never, never>, Record<never, never>>,
    '/forms/Checkbox': RouteRecordInfo<'/forms/Checkbox', '/forms/Checkbox', Record<never, never>, Record<never, never>>,
    '/forms/Datepicker': RouteRecordInfo<'/forms/Datepicker', '/forms/Datepicker', Record<never, never>, Record<never, never>>,
    '/forms/dropdowns/Dropdown': RouteRecordInfo<'/forms/dropdowns/Dropdown', '/forms/dropdowns/Dropdown', Record<never, never>, Record<never, never>>,
    '/forms/dropdowns/Multiselect': RouteRecordInfo<'/forms/dropdowns/Multiselect', '/forms/dropdowns/Multiselect', Record<never, never>, Record<never, never>>,
    '/forms/dropdowns/MultiselectPreview': RouteRecordInfo<'/forms/dropdowns/MultiselectPreview', '/forms/dropdowns/MultiselectPreview', Record<never, never>, Record<never, never>>,
    '/forms/dropdowns/TreeSelect': RouteRecordInfo<'/forms/dropdowns/TreeSelect', '/forms/dropdowns/TreeSelect', Record<never, never>, Record<never, never>>,
    '/forms/FileUploader': RouteRecordInfo<'/forms/FileUploader', '/forms/FileUploader', Record<never, never>, Record<never, never>>,
    '/forms/Form': RouteRecordInfo<'/forms/Form', '/forms/Form', Record<never, never>, Record<never, never>>,
    '/forms/inputs/AutoComplete': RouteRecordInfo<'/forms/inputs/AutoComplete', '/forms/inputs/AutoComplete', Record<never, never>, Record<never, never>>,
    '/forms/inputs/Chips': RouteRecordInfo<'/forms/inputs/Chips', '/forms/inputs/Chips', Record<never, never>, Record<never, never>>,
    '/forms/inputs/FormField': RouteRecordInfo<'/forms/inputs/FormField', '/forms/inputs/FormField', Record<never, never>, Record<never, never>>,
    '/forms/inputs/InlineEditor': RouteRecordInfo<'/forms/inputs/InlineEditor', '/forms/inputs/InlineEditor', Record<never, never>, Record<never, never>>,
    '/forms/inputs/Mask': RouteRecordInfo<'/forms/inputs/Mask', '/forms/inputs/Mask', Record<never, never>, Record<never, never>>,
    '/forms/inputs/Number': RouteRecordInfo<'/forms/inputs/Number', '/forms/inputs/Number', Record<never, never>, Record<never, never>>,
    '/forms/inputs/Text': RouteRecordInfo<'/forms/inputs/Text', '/forms/inputs/Text', Record<never, never>, Record<never, never>>,
    '/forms/inputs/TextArea': RouteRecordInfo<'/forms/inputs/TextArea', '/forms/inputs/TextArea', Record<never, never>, Record<never, never>>,
    '/forms/Listbox': RouteRecordInfo<'/forms/Listbox', '/forms/Listbox', Record<never, never>, Record<never, never>>,
    '/forms/PickList': RouteRecordInfo<'/forms/PickList', '/forms/PickList', Record<never, never>, Record<never, never>>,
    '/forms/RemainingCharacters': RouteRecordInfo<'/forms/RemainingCharacters', '/forms/RemainingCharacters', Record<never, never>, Record<never, never>>,
    '/forms/Scratchpad': RouteRecordInfo<'/forms/Scratchpad', '/forms/Scratchpad', Record<never, never>, Record<never, never>>,
    '/forms/Switch': RouteRecordInfo<'/forms/Switch', '/forms/Switch', Record<never, never>, Record<never, never>>,
    '/guides/Changeset': RouteRecordInfo<'/guides/Changeset', '/guides/Changeset', Record<never, never>, Record<never, never>>,
    '/guides/ForgePlayground': RouteRecordInfo<'/guides/ForgePlayground', '/guides/ForgePlayground', Record<never, never>, Record<never, never>>,
    '/guides/ForgeResolver': RouteRecordInfo<'/guides/ForgeResolver', '/guides/ForgeResolver', Record<never, never>, Record<never, never>>,
    '/guides/Installation': RouteRecordInfo<'/guides/Installation', '/guides/Installation', Record<never, never>, Record<never, never>>,
    '/guides/NewComponent': RouteRecordInfo<'/guides/NewComponent', '/guides/NewComponent', Record<never, never>, Record<never, never>>,
    '/guides/Passthroughs': RouteRecordInfo<'/guides/Passthroughs', '/guides/Passthroughs', Record<never, never>, Record<never, never>>,
    '/guides/Testing': RouteRecordInfo<'/guides/Testing', '/guides/Testing', Record<never, never>, Record<never, never>>,
    '/guides/Validation': RouteRecordInfo<'/guides/Validation', '/guides/Validation', Record<never, never>, Record<never, never>>,
    '/Icons': RouteRecordInfo<'/Icons', '/Icons', Record<never, never>, Record<never, never>>,
    '/layout/Accordion': RouteRecordInfo<'/layout/Accordion', '/layout/Accordion', Record<never, never>, Record<never, never>>,
    '/layout/Alert': RouteRecordInfo<'/layout/Alert', '/layout/Alert', Record<never, never>, Record<never, never>>,
    '/layout/Fieldset': RouteRecordInfo<'/layout/Fieldset', '/layout/Fieldset', Record<never, never>, Record<never, never>>,
    '/layout/Loader': RouteRecordInfo<'/layout/Loader', '/layout/Loader', Record<never, never>, Record<never, never>>,
    '/layout/Navbar': RouteRecordInfo<'/layout/Navbar', '/layout/Navbar', Record<never, never>, Record<never, never>>,
    '/layout/PageHeader': RouteRecordInfo<'/layout/PageHeader', '/layout/PageHeader', Record<never, never>, Record<never, never>>,
    '/layout/Panel': RouteRecordInfo<'/layout/Panel', '/layout/Panel', Record<never, never>, Record<never, never>>,
    '/layout/Stepper': RouteRecordInfo<'/layout/Stepper', '/layout/Stepper', Record<never, never>, Record<never, never>>,
    '/layout/Tabs': RouteRecordInfo<'/layout/Tabs', '/layout/Tabs', Record<never, never>, Record<never, never>>,
    '/misc/Badge': RouteRecordInfo<'/misc/Badge', '/misc/Badge', Record<never, never>, Record<never, never>>,
    '/misc/Tag': RouteRecordInfo<'/misc/Tag', '/misc/Tag', Record<never, never>, Record<never, never>>,
    '/overlay/ConfirmModal': RouteRecordInfo<'/overlay/ConfirmModal', '/overlay/ConfirmModal', Record<never, never>, Record<never, never>>,
    '/overlay/ConfirmPopup': RouteRecordInfo<'/overlay/ConfirmPopup', '/overlay/ConfirmPopup', Record<never, never>, Record<never, never>>,
    '/overlay/Drawer': RouteRecordInfo<'/overlay/Drawer', '/overlay/Drawer', Record<never, never>, Record<never, never>>,
    '/overlay/Modal': RouteRecordInfo<'/overlay/Modal', '/overlay/Modal', Record<never, never>, Record<never, never>>,
    '/overlay/Popover': RouteRecordInfo<'/overlay/Popover', '/overlay/Popover', Record<never, never>, Record<never, never>>,
    '/overlay/Toast': RouteRecordInfo<'/overlay/Toast', '/overlay/Toast', Record<never, never>, Record<never, never>>,
    '/overlay/Tooltip': RouteRecordInfo<'/overlay/Tooltip', '/overlay/Tooltip', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/buttons/ActionButton.vue': {
      routes: '/buttons/ActionButton'
      views: never
    }
    'src/pages/buttons/Button.vue': {
      routes: '/buttons/Button'
      views: never
    }
    'src/pages/buttons/ButtonGroup.vue': {
      routes: '/buttons/ButtonGroup'
      views: never
    }
    'src/pages/buttons/Link.vue': {
      routes: '/buttons/Link'
      views: never
    }
    'src/pages/buttons/SelectButton.vue': {
      routes: '/buttons/SelectButton'
      views: never
    }
    'src/pages/buttons/SplitButton.vue': {
      routes: '/buttons/SplitButton'
      views: never
    }
    'src/pages/buttons/ToggleButton.vue': {
      routes: '/buttons/ToggleButton'
      views: never
    }
    'src/pages/Changelog.vue': {
      routes: '/Changelog'
      views: never
    }
    'src/pages/Colours.vue': {
      routes: '/Colours'
      views: never
    }
    'src/pages/data/Chart.vue': {
      routes: '/data/Chart'
      views: never
    }
    'src/pages/data/DataView.vue': {
      routes: '/data/DataView'
      views: never
    }
    'src/pages/data/Progress.vue': {
      routes: '/data/Progress'
      views: never
    }
    'src/pages/data/StatWidget.vue': {
      routes: '/data/StatWidget'
      views: never
    }
    'src/pages/data/Table.vue': {
      routes: '/data/Table'
      views: never
    }
    'src/pages/data/Tile.vue': {
      routes: '/data/Tile'
      views: never
    }
    'src/pages/data/Tree.vue': {
      routes: '/data/Tree'
      views: never
    }
    'src/pages/data/TreeTable.vue': {
      routes: '/data/TreeTable'
      views: never
    }
    'src/pages/examples/CodeTesting.vue': {
      routes: '/examples/CodeTesting'
      views: never
    }
    'src/pages/examples/components/ExampleAutoComplete.vue': {
      routes: '/examples/components/ExampleAutoComplete'
      views: never
    }
    'src/pages/examples/components/ExampleButton.vue': {
      routes: '/examples/components/ExampleButton'
      views: never
    }
    'src/pages/examples/components/ExampleConfirmDialogue.vue': {
      routes: '/examples/components/ExampleConfirmDialogue'
      views: never
    }
    'src/pages/examples/components/ExampleConfirmPopup.vue': {
      routes: '/examples/components/ExampleConfirmPopup'
      views: never
    }
    'src/pages/examples/components/ExampleDataView.vue': {
      routes: '/examples/components/ExampleDataView'
      views: never
    }
    'src/pages/examples/components/ExampleDrawer.vue': {
      routes: '/examples/components/ExampleDrawer'
      views: never
    }
    'src/pages/examples/components/ExampleFileUploader.vue': {
      routes: '/examples/components/ExampleFileUploader'
      views: never
    }
    'src/pages/examples/components/ExampleListbox.vue': {
      routes: '/examples/components/ExampleListbox'
      views: never
    }
    'src/pages/examples/components/ExampleModal.vue': {
      routes: '/examples/components/ExampleModal'
      views: never
    }
    'src/pages/examples/components/ExampleModalValidation.vue': {
      routes: '/examples/components/ExampleModalValidation'
      views: never
    }
    'src/pages/examples/components/ExampleNavBar.vue': {
      routes: '/examples/components/ExampleNavBar'
      views: never
    }
    'src/pages/examples/components/ExamplePickList.vue': {
      routes: '/examples/components/ExamplePickList'
      views: never
    }
    'src/pages/examples/components/ExampleScratchpad.vue': {
      routes: '/examples/components/ExampleScratchpad'
      views: never
    }
    'src/pages/examples/components/ExampleSelectBool.vue': {
      routes: '/examples/components/ExampleSelectBool'
      views: never
    }
    'src/pages/examples/components/ExampleTableExapandableGroup.vue': {
      routes: '/examples/components/ExampleTableExapandableGroup'
      views: never
    }
    'src/pages/examples/components/ExampleTableGroup.vue': {
      routes: '/examples/components/ExampleTableGroup'
      views: never
    }
    'src/pages/examples/components/ExampleTableWithColumnGroups.vue': {
      routes: '/examples/components/ExampleTableWithColumnGroups'
      views: never
    }
    'src/pages/examples/components/FormExamples.vue': {
      routes: '/examples/components/FormExamples'
      views: never
    }
    'src/pages/examples/components/SimpleFormValidationExample.vue': {
      routes: '/examples/components/SimpleFormValidationExample'
      views: never
    }
    'src/pages/examples/components/SimpleModalValidationExample.vue': {
      routes: '/examples/components/SimpleModalValidationExample'
      views: never
    }
    'src/pages/forms/Checkbox.vue': {
      routes: '/forms/Checkbox'
      views: never
    }
    'src/pages/forms/Datepicker.vue': {
      routes: '/forms/Datepicker'
      views: never
    }
    'src/pages/forms/dropdowns/Dropdown.vue': {
      routes: '/forms/dropdowns/Dropdown'
      views: never
    }
    'src/pages/forms/dropdowns/Multiselect.vue': {
      routes: '/forms/dropdowns/Multiselect'
      views: never
    }
    'src/pages/forms/dropdowns/MultiselectPreview.vue': {
      routes: '/forms/dropdowns/MultiselectPreview'
      views: never
    }
    'src/pages/forms/dropdowns/TreeSelect.vue': {
      routes: '/forms/dropdowns/TreeSelect'
      views: never
    }
    'src/pages/forms/FileUploader.vue': {
      routes: '/forms/FileUploader'
      views: never
    }
    'src/pages/forms/Form.vue': {
      routes: '/forms/Form'
      views: never
    }
    'src/pages/forms/inputs/AutoComplete.vue': {
      routes: '/forms/inputs/AutoComplete'
      views: never
    }
    'src/pages/forms/inputs/Chips.vue': {
      routes: '/forms/inputs/Chips'
      views: never
    }
    'src/pages/forms/inputs/FormField.vue': {
      routes: '/forms/inputs/FormField'
      views: never
    }
    'src/pages/forms/inputs/InlineEditor.vue': {
      routes: '/forms/inputs/InlineEditor'
      views: never
    }
    'src/pages/forms/inputs/Mask.vue': {
      routes: '/forms/inputs/Mask'
      views: never
    }
    'src/pages/forms/inputs/Number.vue': {
      routes: '/forms/inputs/Number'
      views: never
    }
    'src/pages/forms/inputs/Text.vue': {
      routes: '/forms/inputs/Text'
      views: never
    }
    'src/pages/forms/inputs/TextArea.vue': {
      routes: '/forms/inputs/TextArea'
      views: never
    }
    'src/pages/forms/Listbox.vue': {
      routes: '/forms/Listbox'
      views: never
    }
    'src/pages/forms/PickList.vue': {
      routes: '/forms/PickList'
      views: never
    }
    'src/pages/forms/RemainingCharacters.vue': {
      routes: '/forms/RemainingCharacters'
      views: never
    }
    'src/pages/forms/Scratchpad.vue': {
      routes: '/forms/Scratchpad'
      views: never
    }
    'src/pages/forms/Switch.vue': {
      routes: '/forms/Switch'
      views: never
    }
    'src/pages/guides/Changeset.vue': {
      routes: '/guides/Changeset'
      views: never
    }
    'src/pages/guides/ForgePlayground.vue': {
      routes: '/guides/ForgePlayground'
      views: never
    }
    'src/pages/guides/ForgeResolver.vue': {
      routes: '/guides/ForgeResolver'
      views: never
    }
    'src/pages/guides/Installation.vue': {
      routes: '/guides/Installation'
      views: never
    }
    'src/pages/guides/NewComponent.vue': {
      routes: '/guides/NewComponent'
      views: never
    }
    'src/pages/guides/Passthroughs.vue': {
      routes: '/guides/Passthroughs'
      views: never
    }
    'src/pages/guides/Testing.vue': {
      routes: '/guides/Testing'
      views: never
    }
    'src/pages/guides/Validation.vue': {
      routes: '/guides/Validation'
      views: never
    }
    'src/pages/Icons.vue': {
      routes: '/Icons'
      views: never
    }
    'src/pages/layout/Accordion.vue': {
      routes: '/layout/Accordion'
      views: never
    }
    'src/pages/layout/Alert.vue': {
      routes: '/layout/Alert'
      views: never
    }
    'src/pages/layout/Fieldset.vue': {
      routes: '/layout/Fieldset'
      views: never
    }
    'src/pages/layout/Loader.vue': {
      routes: '/layout/Loader'
      views: never
    }
    'src/pages/layout/Navbar.vue': {
      routes: '/layout/Navbar'
      views: never
    }
    'src/pages/layout/PageHeader.vue': {
      routes: '/layout/PageHeader'
      views: never
    }
    'src/pages/layout/Panel.vue': {
      routes: '/layout/Panel'
      views: never
    }
    'src/pages/layout/Stepper.vue': {
      routes: '/layout/Stepper'
      views: never
    }
    'src/pages/layout/Tabs.vue': {
      routes: '/layout/Tabs'
      views: never
    }
    'src/pages/misc/Badge.vue': {
      routes: '/misc/Badge'
      views: never
    }
    'src/pages/misc/Tag.vue': {
      routes: '/misc/Tag'
      views: never
    }
    'src/pages/overlay/ConfirmModal.vue': {
      routes: '/overlay/ConfirmModal'
      views: never
    }
    'src/pages/overlay/ConfirmPopup.vue': {
      routes: '/overlay/ConfirmPopup'
      views: never
    }
    'src/pages/overlay/Drawer.vue': {
      routes: '/overlay/Drawer'
      views: never
    }
    'src/pages/overlay/Modal.vue': {
      routes: '/overlay/Modal'
      views: never
    }
    'src/pages/overlay/Popover.vue': {
      routes: '/overlay/Popover'
      views: never
    }
    'src/pages/overlay/Toast.vue': {
      routes: '/overlay/Toast'
      views: never
    }
    'src/pages/overlay/Tooltip.vue': {
      routes: '/overlay/Tooltip'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
