/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DragDropArea: typeof import('./src/components/file-uploader/components/DragDropArea.vue')['default']
    FileInfo: typeof import('./src/components/file-uploader/components/FileInfo.vue')['default']
    FileInputInfo: typeof import('./src/components/file-uploader/components/FileInputInfo.vue')['default']
    ForgeActionButton: typeof import('./src/components/ForgeActionButton.vue')['default']
    ForgeAlert: typeof import('./src/components/ForgeAlert.vue')['default']
    ForgeAutoComplete: typeof import('./src/components/ForgeAutoComplete.vue')['default']
    ForgeCheckbox: typeof import('./src/components/ForgeCheckbox.vue')['default']
    ForgeChip: typeof import('./src/components/ForgeChip.vue')['default']
    ForgeColumnCustomiser: typeof import('./src/components/table/ForgeColumnCustomiser.vue')['default']
    ForgeDatepicker: typeof import('./src/components/ForgeDatepicker.vue')['default']
    ForgeFileUploader: typeof import('./src/components/file-uploader/ForgeFileUploader.vue')['default']
    ForgeFilterHeader: typeof import('./src/components/table/ForgeFilterHeader.vue')['default']
    ForgeForm: typeof import('./src/components/ForgeForm.vue')['default']
    ForgeFormField: typeof import('./src/components/ForgeFormField.vue')['default']
    ForgeInlineEditor: typeof import('./src/components/ForgeInlineEditor.vue')['default']
    ForgeLink: typeof import('./src/components/ForgeLink.vue')['default']
    ForgeLoader: typeof import('./src/components/ForgeLoader.vue')['default']
    ForgeModal: typeof import('./src/components/ForgeModal.vue')['default']
    ForgeMultiSelectPreview: typeof import('./src/components/ForgeMultiSelectPreview.vue')['default']
    ForgeNavbar: typeof import('./src/components/ForgeNavbar.vue')['default']
    ForgePageHeader: typeof import('./src/components/ForgePageHeader.vue')['default']
    ForgePaginationHeader: typeof import('./src/components/table/ForgePaginationHeader.vue')['default']
    ForgePanel: typeof import('./src/components/ForgePanel.vue')['default']
    ForgeProgressBar: typeof import('./src/components/ForgeProgressBar.vue')['default']
    ForgeRemainingCharacters: typeof import('./src/components/ForgeRemainingCharacters.vue')['default']
    ForgeScratchpad: typeof import('./src/components/ForgeScratchpad.vue')['default']
    ForgeSelectButton: typeof import('./src/components/ForgeSelectButton.vue')['default']
    ForgeStatWidget: typeof import('./src/components/ForgeStatWidget.vue')['default']
    ForgeStepper: typeof import('./src/components/ForgeStepper.vue')['default']
    ForgeTable: typeof import('./src/components/table/ForgeTable.vue')['default']
    ForgeTile: typeof import('./src/components/ForgeTile.vue')['default']
    ForgeToggleButton: typeof import('./src/components/ForgeToggleButton.vue')['default']
    ForgeTreeTable: typeof import('./src/components/ForgeTreeTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadButton: typeof import('./src/components/file-uploader/components/UploadButton.vue')['default']
    UploadStatus: typeof import('./src/components/file-uploader/components/UploadStatus.vue')['default']
  }
}
